version: '3.0'

services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
      - ./data:/data:ro
    ports:
      - 8000:8000
    env_file:
      - ./.env.test
    depends_on:
      - database
    
  database:
    image: postgres
    env_file:
      - ./.env.test
    container_name: database
    volumes:
      - dbdata:/var/lib/postgresql/data
    
volumes:
  dbdata: