# Generated by Django 5.1.1 on 2024-10-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_options_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
    ]
